x-app: &app
  build:
    context: .
    args:
      TRUFFLERUBY_VERSION: '24.0.1'
  image: truffleruby-test:1.0.0
  tmpfs:
    - /tmp
    - /app/tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - history:/usr/local/hist
  environment: &backend_environment
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/TestAR
    TRUFFLERUBYOPT: --jvm

services:
  ruby:
    <<: *backend
    command: ruby ./benchmark.rb

volumes:
  bundle:
  history:
  postgres: