x-app: &app
  build:
    context: .
    dockerfile: ../../dockerfiles/jruby/Dockerfile
    args:
      JRUBY_VERSION: '9.4.9.0'
  image: truffleruby-test-sqlite:1.0.0
  tmpfs:
    - /tmp
    - /app/tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
  environment: &backend_environment
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/TestAR
    TRUFFLERUBYOPT: --experimental-options --cexts-lock=false

services:
  ruby:
    <<: *backend
    command: ruby ./benchmark.rb

volumes:
  bundle: